import = ["~/.config/alacritty/rose-pine.toml"]

[window]
opacity = 1

[font]
size = 11
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "BoldItalic"}

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "off" }
